name: Deploy Spring Boot Application
description: Deploy the Docker image to an AWS EC2 instance.
inputs:
  image_name:
    description: Docker image name to deploy
    required: true
    type: string
  docker_username:
    required: true
  docker_password:
    required: true
    
jobs:
  deploy:
    runs-on: [aws-ec2]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.docker_username }}
          password: ${{ inputs.docker_password }}
          
      - name: pull image from docker hub
        shell: bash
        run: docker pull ${{ inputs.image_name }}
      - name: Delete old container
        shell: bash
        run: |
          docker rm -f spring-petclinic-container || echo "No existing container to remove"
      - name: Run docker container
        shell: bash
        run: docker run -d -p 8080:8080 --name spring-petclinic-container ${{ inputs.image_name }}
