name: Deploy Spring Boot Application
# description: Deploy the Docker image to an AWS EC2 instance.
on:
  workflow_call:
    inputs:
      image_name:
        description: Docker image name to deploy
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
        
jobs:
  deploy:
    runs-on: [aws-ec2]
    steps:
      - name: login to docker hub
        shell: bash
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
      - name: pull image from docker hub
        shell: bash
        run: docker pull ${{ inputs.image_name}}
      - name: Delete old container
        shell: bash
        run: |
          docker rm -f spring-petclinic-container || echo "No existing container to remove"
      - name: Run docker container
        shell: bash
        run: docker run -d -p 8080:8080 --name spring-petclinic-container ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name}}
